onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider RISCV_CORE
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/clk_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/rst_ni
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/clock_en_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/test_en_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/boot_addr_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/core_id_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/cluster_id_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/instr_req_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/instr_gnt_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/instr_rvalid_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/instr_addr_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/instr_rdata_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_req_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_gnt_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_rvalid_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_we_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_be_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_addr_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_wdata_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_rdata_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/data_err_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_req_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_ready_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_gnt_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_operands_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_op_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_type_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_flags_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_valid_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_result_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/apu_master_flags_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/irq_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/irq_id_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/irq_ack_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/irq_id_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/irq_sec_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/sec_lvl_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_req_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_gnt_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_rvalid_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_addr_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_we_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_wdata_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_rdata_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_halted_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_halt_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/debug_resume_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/fetch_enable_i
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/core_busy_o
add wave -noupdate /tb/top_i/core_region_i/CORE/RISCV_CORE/ext_perf_counters_i
add wave -noupdate -divider {Register File}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[0]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[1]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[2]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[3]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[4]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[5]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[6]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[7]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[8]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[9]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[10]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[11]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[12]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[13]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[14]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[15]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[16]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[17]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[18]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[19]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[20]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[21]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[22]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[23]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[24]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[25]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[26]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[27]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[28]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[29]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[30]}
add wave -noupdate {/tb/top_i/core_region_i/CORE/RISCV_CORE/id_stage_i/registers_i/mem[31]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {710999285 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 526
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1642496 ps}
